[workspace]
resolver = "3"
members = ["business-core", "map-api", "resource-api"]

[workspace.dependencies]
business-core = { path = "./business-core" }
serde = { version = "1.0", features = ["derive"] }
